package com.btpn.shopping.domain;
// Generated May 7, 2019 9:56:28 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShoppingCartId generated by hbm2java
 */
@Embeddable
public class ShoppingCartId implements java.io.Serializable {

    private long idUser;
    private long idProduct;

    public ShoppingCartId() {
    }

    public ShoppingCartId(long idUser, long idProduct) {
        this.idUser = idUser;
        this.idProduct = idProduct;
    }

    @Column(name = "id_user", nullable = false)
    public long getIdUser() {
        return this.idUser;
    }

    public void setIdUser(long idUser) {
        this.idUser = idUser;
    }

    @Column(name = "id_product", nullable = false)
    public long getIdProduct() {
        return this.idProduct;
    }

    public void setIdProduct(long idProduct) {
        this.idProduct = idProduct;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ShoppingCartId)) {
            return false;
        }
        ShoppingCartId castOther = (ShoppingCartId) other;

        return (this.getIdUser() == castOther.getIdUser())
                && (this.getIdProduct() == castOther.getIdProduct());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getIdUser();
        result = 37 * result + (int) this.getIdProduct();
        return result;
    }

}
